# production
server:
  host: 127.0.0.1
  port: 4000
  timezone: 'UTC'
  cluster: true
  base_url: http://coke/

db:
  db: coke
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

cookie:
  secret: kimjkCFGyblDTk09cga93313dc222b098ujmnhFQ

session:
  # optional, default: sessions
  collection:

logs:
  - error

libs:

# libs that must run after server started
started:

# cdn setting
asset_host:
  # - http://assets1.example.com
  # - http://assets2.example.com

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:
  secret:
  s3:
    bucket: assets.coke
