# development
server:
  host: 127.0.0.1
  port: 4000
  timezone: 'UTC'
  cluster: false
  base_url: http://dev.coke/

db:
  db: coke-dev
  # optional, default: localhost
  host:
  # optional, default: 27017
  port:
  # optional
  username:
  # optional
  password:

cookie:
  secret: kimjkCFGyblDTk09cga93313dc222b098ujmnhFQ

session:
  # optional, default: sessions
  collection:

logs:
  - sys
  - request
  - response
  - error
  - debug

libs:

# libs that must run after server started
started:
  - socket.io

aws:
  # your aws key & secret, those must not be empty if you set s3 option to true in assets config
  key:
  secret:
  s3:
    bucket: assets.dev.coke
